# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QA4GfL58pky-DlKEs1Hwun8VqQqHMxaL
"""

print("hello")
print("Strange!!!")