# -*- coding: utf-8 -*-
"""streamlit_hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bGupUEUQIFty9lMEfiD7m1d5qD53_nwy
"""

print('hello')